/// A declaration of an evolvable function, generated by the `evolvable!` macro.
///
/// Contains the metadata needed to create the temporary dylib crate and validate
/// LLM-generated code against the expected function signatures.
pub struct EvolvableDecl {
    /// Function name (e.g., `"step"`).
    pub name: &'static str,
    /// Formatted signature string (e.g., `"fn step(counter: &mut usize)"`).
    pub signature: &'static str,
    /// Full source code for the dylib, including `#[unsafe(no_mangle)]` and `pub`.
    pub default_source: &'static str,
}
