// SPDX-License-Identifier: MPL-2.0
use std::{
    fmt,
    path::PathBuf,
    sync::atomic::AtomicPtr,
};

/// A declaration of an evolvable function, generated by the `evolvable!` macro.
///
/// Contains the metadata needed to create the temporary dylib crate and validate
/// LLM-generated code against the expected function signatures.
pub struct EvolvableDecl {
    /// Function name (e.g., `"step"`).
    pub name: &'static str,
    /// Formatted signature string (e.g., `"fn step(counter: &mut usize)"`).
    pub signature: &'static str,
    /// Full source code for the dylib, including `#[unsafe(no_mangle)]` and `pub`.
    pub full_source: &'static str,
    /// Pointer to the per-function `AtomicPtr<()>` that caches the loaded symbol.
    /// Updated by the runtime on init and each reload.
    pub fn_ptr: &'static AtomicPtr<()>,
}

impl fmt::Debug for EvolvableDecl {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("EvolvableDecl")
            .field("name", &self.name)
            .field("signature", &self.signature)
            .field("full_source", &FullSource(self.full_source))
            .field("fn_ptr", &self.fn_ptr)
            .finish()
    }
}

/// Configuration for the temporary dylib crate compiled by [`crate::Runtime`].
///
/// The generated dylib is a normal Cargo crate. When an evolvable signature uses
/// host-defined or dependency-defined types, configure the dylib with matching
/// dependencies and imports instead of copying type source into the dylib.
///
/// [`DylibConfig::host_package`] is the ergonomic path for examples and
/// single-package applications: it depends on the current package's library
/// target as the crate alias `host` and prepends `use host::prelude::*;`.
#[derive(Debug, Clone)]
pub struct DylibConfig {
    /// Compilation profile (`debug` or `release`).
    pub profile: crate::Profile,
    /// Rust source snippets prepended to every generated dylib source file.
    /// Typically contains imports such as `use host::prelude::*;`.
    pub prelude: Vec<String>,
    /// Dependencies added to the generated dylib's `Cargo.toml`.
    pub dependencies: Vec<DylibDependency>,
}

impl DylibConfig {
    /// Create a config for a Cargo package's library target.
    ///
    /// The dylib gets a path dependency on `package_dir`, renamed to the crate
    /// alias `host`, and imports `host::prelude::*` by default.
    ///
    /// This assumes the package has a `lib` target. Binary-only packages should
    /// move shared boundary types and methods into `src/lib.rs`.
    #[must_use]
    pub fn host_package(
        profile: crate::Profile,
        package_name: impl Into<String>,
        package_dir: impl Into<PathBuf>,
    ) -> Self {
        Self {
            profile,
            prelude: vec!["use host::prelude::*;".to_string()],
            dependencies: vec![DylibDependency::path_renamed(
                "host",
                package_name,
                package_dir,
            )],
        }
    }

    /// Create a config with no dylib dependencies and the supplied profile.
    #[must_use]
    pub fn standalone(profile: crate::Profile) -> Self {
        Self {
            profile,
            prelude: Vec::new(),
            dependencies: Vec::new(),
        }
    }

    /// Add a Rust source snippet to the generated dylib prelude.
    #[must_use]
    pub fn with_prelude(mut self, prelude: impl Into<String>) -> Self {
        self.prelude.push(prelude.into());
        self
    }

    /// Add a dependency to the generated dylib crate.
    #[must_use]
    pub fn with_dependency(mut self, dependency: DylibDependency) -> Self {
        self.dependencies.push(dependency);
        self
    }
}

impl From<crate::Profile> for DylibConfig {
    fn from(profile: crate::Profile) -> Self {
        Self::standalone(profile)
    }
}

/// A dependency entry for the generated dylib crate's `Cargo.toml`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DylibDependency {
    /// Dependency key in the generated `Cargo.toml`, e.g. `host`.
    pub name: String,
    /// Optional package rename, e.g. `{ package = "my-app", path = "..." }`.
    pub package: Option<String>,
    /// Local path dependency.
    pub path: Option<PathBuf>,
    /// Registry version requirement.
    pub version: Option<String>,
    /// Enabled features.
    pub features: Vec<String>,
    /// Whether default features are enabled.
    pub default_features: bool,
}

impl DylibDependency {
    /// Create a path dependency.
    #[must_use]
    pub fn path(name: impl Into<String>, path: impl Into<PathBuf>) -> Self {
        Self {
            name: name.into(),
            package: None,
            path: Some(path.into()),
            version: None,
            features: Vec::new(),
            default_features: true,
        }
    }

    /// Create a path dependency with a crate rename.
    #[must_use]
    pub fn path_renamed(
        name: impl Into<String>,
        package: impl Into<String>,
        path: impl Into<PathBuf>,
    ) -> Self {
        Self {
            name: name.into(),
            package: Some(package.into()),
            path: Some(path.into()),
            version: None,
            features: Vec::new(),
            default_features: true,
        }
    }

    /// Create a registry dependency.
    #[must_use]
    pub fn version(name: impl Into<String>, version: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            package: None,
            path: None,
            version: Some(version.into()),
            features: Vec::new(),
            default_features: true,
        }
    }

    /// Set the package name used when it differs from the dependency key.
    #[must_use]
    pub fn with_package(mut self, package: impl Into<String>) -> Self {
        self.package = Some(package.into());
        self
    }

    /// Set features for this dependency.
    #[must_use]
    pub fn with_features(mut self, features: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.features = features.into_iter().map(Into::into).collect();
        self
    }

    /// Enable or disable default features for this dependency.
    #[must_use]
    pub fn with_default_features(mut self, enabled: bool) -> Self {
        self.default_features = enabled;
        self
    }
}

/// Wrapper around a multi-line Rust source string that renders with real line
/// breaks under pretty-print (`{:#?}`), instead of the default escaped
/// single-line form.
///
/// Behaves like a `&str` for all practical purposes: dereferences to `str`,
/// implements `AsRef<str>` and `Display` (which writes the source verbatim).
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct FullSource<'a>(pub &'a str);

impl AsRef<str> for FullSource<'static> {
    #[inline(always)]
    fn as_ref(&self) -> &str {
        self.0
    }
}

impl fmt::Debug for FullSource<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if f.alternate() {
            // Render each source line indented one level deeper than the
            // surrounding context. Avoid emitting a trailing newline so any
            // following punctuation (e.g. the `,` from `debug_struct` /
            // `debug_list`) sits directly after the last source line.
            let trimmed = self.0.trim_end_matches('\n');
            for line in trimmed.lines() {
                f.write_str("\n    ")?;
                f.write_str(line)?;
            }
            Ok(())
        } else {
            fmt::Debug::fmt(self.0, f)
        }
    }
}

impl fmt::Display for FullSource<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.0)
    }
}

impl<'a> From<&'a str> for FullSource<'a> {
    #[inline]
    fn from(s: &'a str) -> Self {
        Self(s)
    }
}

// SAFETY: AtomicPtr is Send+Sync, and the other fields are &'static str.
unsafe impl Send for EvolvableDecl {}
unsafe impl Sync for EvolvableDecl {}

#[cfg(test)]
mod tests {
    use std::ptr;

    use super::*;

    #[test]
    fn debug_renders_full_source_with_real_line_breaks() {
        static PTR: AtomicPtr<()> = AtomicPtr::new(ptr::null_mut());
        let decl = EvolvableDecl {
            name: "step",
            signature: "fn step(counter: &mut usize)",
            full_source: "/// Should increment the counter by a value in the range 5..20\n\
                          #[unsafe(no_mangle)]\n\
                          pub fn step(counter: &mut usize) {\n    \
                              *counter += 1;\n\
                          }\n",
            fn_ptr: &PTR,
        };

        let pretty = format!("{decl:#?}");
        // Source lines should be present verbatim (no `\n` escapes).
        assert!(pretty.contains("\n        #[unsafe(no_mangle)]\n"));
        assert!(pretty.contains("\n        pub fn step(counter: &mut usize) {\n"));
        assert!(pretty.contains("\n            *counter += 1;\n"));
        assert!(!pretty.contains(r"\n"));
    }

    #[test]
    fn full_source_vec_pretty_prints_each_entry() {
        let sources = vec![
            FullSource("#[unsafe(no_mangle)]\npub fn a() {}\n"),
            FullSource("#[unsafe(no_mangle)]\npub fn b() {\n    todo!()\n}\n"),
        ];

        let pretty = format!("{sources:#?}");
        assert!(pretty.contains("\n        #[unsafe(no_mangle)]\n"));
        assert!(pretty.contains("\n        pub fn a() {}"));
        assert!(pretty.contains("\n        pub fn b() {\n"));
        assert!(pretty.contains("\n            todo!()\n"));
        assert!(!pretty.contains(r"\n"));
    }

    #[test]
    fn full_source_as_str() {
        let source = FullSource("Hello");
        assert_eq!(&source.to_string(), "Hello");
    }
}
