//! The runtime module contains the primary `Runtime`,
//! managing the lifecycle of the temporary dylib crate: creation, compilation,
//! loading, and hot-reloading.

use std::{
    collections::hash_map::DefaultHasher,
    ffi::CString,
    fmt::Write,
    hash::{
        Hash,
        Hasher,
    },
    path::{
        Path,
        PathBuf,
    },
    sync::{
        Mutex,
        OnceLock,
        atomic::{
            AtomicU64,
            Ordering,
        },
    },
};

use libloading::Library;
use minstant::Instant;
use rig::{
    agent::Agent,
    completion::{
        CompletionModel,
        Prompt,
    },
};
use tracing::{
    info,
    warn,
};

use crate::{
    EvolvableDecl,
    compiler::compile_dylib,
    error::{
        Error,
        Result,
    },
    parser::parse_rust_code,
    validation::validate_generated_ast,
};

/// Singleton runtime instance.
static RUNTIME: OnceLock<Runtime> = OnceLock::new();

// ---------- debug-mode call counter ----------
//
// Tracks in-flight evolvable function calls so that `evolve()` can assert
// none are running. Compiled away entirely in release builds — zero overhead.

#[cfg(debug_assertions)]
static IN_FLIGHT_CALLS: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

/// RAII guard that decrements the in-flight call counter on drop.
/// Only exists in debug builds.
#[cfg(debug_assertions)]
pub struct CallGuard;

#[cfg(debug_assertions)]
impl Drop for CallGuard {
    fn drop(&mut self) {
        IN_FLIGHT_CALLS.fetch_sub(1, Ordering::Release);
    }
}

/// Increment the in-flight call counter and return a guard that decrements
/// it on drop (including during unwind). Debug builds only.
#[cfg(debug_assertions)]
pub fn enter_call() -> CallGuard {
    IN_FLIGHT_CALLS.fetch_add(1, Ordering::Acquire);
    CallGuard
}

// -------------------------------------------------

/// Manages the lifecycle of the temporary dylib crate: creation, compilation,
/// loading, and hot-reloading.
///
/// Function dispatch is lock-free: each evolvable function reads its cached
/// pointer via a single `AtomicPtr::load`.
///
/// # Contract
///
/// **All evolvable function calls must have returned before [`Runtime::evolve_with_backpressure`]
/// is called.** This is the natural shape of the feedback loop — run functions,
/// collect results, evolve, repeat. The contract is enforced with an assertion
/// in debug builds and is zero-cost in release.
pub struct Runtime {
    /// Path to the temporary dylib crate directory.
    crate_dir: PathBuf,
    /// Path to the compiled `.so` / `.dylib` / `.dll` file.
    so_path: PathBuf,
    /// Monotonically increasing version counter for versioned `.so` paths
    /// to defeat `dlopen` caching.
    version: AtomicU64,
    /// Function signatures for validation of LLM-generated code.
    fn_sigs: Vec<String>,
    /// The currently loaded library.
    /// Safe to replace because the caller guarantees no in-flight calls
    /// during evolution. The Mutex is only taken during reload, never on
    /// the hot path.
    library: Mutex<Option<Library>>,
    /// Declarations (kept for fn_ptr updates on reload).
    decls: &'static [EvolvableDecl],
}

/// Look up all declared symbols in `lib` and store their addresses
/// in the corresponding `AtomicPtr` fields of each declaration.
///
/// # Safety
///
/// The caller must ensure `lib` is a valid loaded library containing
/// symbols with signatures matching the declarations.
unsafe fn update_fn_ptrs(lib: &Library, decls: &[EvolvableDecl]) -> Result<()> {
    for decl in decls {
        let c_name =
            CString::new(decl.name).expect("function name must not contain interior NUL bytes");
        let sym: libloading::Symbol<*const ()> = unsafe {
            lib.get(c_name.as_bytes_with_nul())
                .map_err(|e| Error::DylibLoad(format!("symbol '{}' not found: {e}", decl.name)))?
        };
        decl.fn_ptr.store(*sym as *mut (), Ordering::Release);
    }
    Ok(())
}

impl Runtime {
    /// Initialize the symbiont runtime.
    ///
    /// Creates a temporary dylib crate from the declarations generated by `evolvable!`,
    /// compiles it, and loads the resulting shared library.
    ///
    /// # Panics
    ///
    /// Panics if called more than once.
    pub async fn init(decls: &'static [EvolvableDecl]) -> Result<&'static Runtime> {
        if decls.is_empty() {
            return Err(Error::NoEvolvableFunctions);
        }

        let fn_sigs = Vec::from_iter(decls.iter().map(|d| d.signature.to_string()));

        // Create a stable temp directory based on function names
        let mut hasher = DefaultHasher::new();
        for d in decls {
            d.name.hash(&mut hasher);
        }
        let hash = hasher.finish();
        let crate_dir = std::env::temp_dir().join(format!("symbiont-evolvable-{hash:x}"));
        std::fs::create_dir_all(crate_dir.join("src"))?;

        // Write Cargo.toml
        let cargo_toml = generate_cargo_toml();
        std::fs::write(crate_dir.join("Cargo.toml"), cargo_toml)?;

        // Write src/lib.rs from all default_source entries
        let lib_rs = generate_lib_rs(decls);
        std::fs::write(crate_dir.join("src").join("lib.rs"), &lib_rs)?;
        info!("Created temp dylib crate at {}", crate_dir.display());

        // Compile
        compile_dylib(&crate_dir).await?;

        // Find and load the .so
        let so_path = find_so(&crate_dir)?;
        let lib = unsafe {
            Library::new(&so_path).map_err(|e| {
                Error::DylibLoad(format!("Failed to load {}: {e}", so_path.display()))
            })?
        };

        // Cache function pointers (lock-free after this point)
        unsafe { update_fn_ptrs(&lib, decls)? };

        let runtime = Runtime {
            crate_dir,
            so_path,
            version: AtomicU64::new(1),
            fn_sigs,
            library: Mutex::new(Some(lib)),
            decls,
        };

        RUNTIME
            .set(runtime)
            .map_err(|_| Error::AlreadyInitialized)?;
        Ok(RUNTIME.get().expect("just set"))
    }

    /// Get the function signature strings for all evolvable functions.
    pub fn fn_sigs(&self) -> &[String] {
        &self.fn_sigs
    }

    /// Generate LLM response, then parse, validate, compile, and hot-swap.
    ///
    /// # Contract
    ///
    /// All evolvable function calls must have returned before this is called.
    /// In debug builds this is enforced with an assertion; in release it is
    /// the caller's responsibility.
    async fn evolve<CompletionModelT>(
        &self,
        agent: &Agent<CompletionModelT>,
        prompt: &str,
    ) -> Result<()>
    where
        CompletionModelT: CompletionModel + 'static,
    {
        #[cfg(debug_assertions)]
        {
            let in_flight = IN_FLIGHT_CALLS.load(Ordering::Acquire);
            assert!(
                in_flight == 0,
                "evolve() called while {in_flight} evolvable function(s) are still executing. \
                 All callers must return before evolving — this is the feedback loop contract."
            );
        }

        info!("prompt: {prompt}");
        let t0 = Instant::now();
        let llm_response = agent.prompt(prompt).await?;
        let llm_time = t0.elapsed().as_millis();
        info!("llm_response: {llm_response}");

        let t0 = Instant::now();
        // Parse Rust from markdown fences
        let mut ast = parse_rust_code(&llm_response).map_err(|_| Error::CouldNotParseRust)?;

        // Validate signatures match declarations
        validate_generated_ast(&mut ast, &self.fn_sigs)?;

        // Write validated AST to temp crate's lib.rs
        let lib_rs_path = self.crate_dir.join("src").join("lib.rs");
        let formatted = prettyplease::unparse(&ast);
        std::fs::write(&lib_rs_path, &formatted)
            .map_err(|e| Error::WriteLib(format!("Failed to write lib.rs: {e}")))?;
        info!("Wrote evolved lib.rs to {}", lib_rs_path.display());
        let validation_time = t0.elapsed().as_millis();

        // Recompile
        let t0 = Instant::now();
        compile_dylib(&self.crate_dir).await?;
        let compile_time = t0.elapsed().as_millis();

        // Copy .so to versioned path to defeat dlopen caching
        let version = self.version.fetch_add(1, Ordering::SeqCst);
        let versioned_so = self.crate_dir.join(format!(
            "libsymbiont_evolvable_v{version}{}",
            dylib_extension()
        ));
        std::fs::copy(&self.so_path, &versioned_so)?;

        // Load new library
        let new_lib = unsafe {
            Library::new(&versioned_so).map_err(|e| {
                Error::DylibLoad(format!("Failed to load {}: {e}", versioned_so.display()))
            })?
        };

        // Update cached function pointers (atomic stores with Release ordering).
        unsafe { update_fn_ptrs(&new_lib, self.decls)? };

        // Replace the library. Safe to drop the old one because the caller
        // guarantees no evolvable functions are executing (feedback loop contract).
        *self.library.lock().expect("library Mutex poisoned") = Some(new_lib);

        info!(
            "Hot-reloaded evolvable dylib (version {version}). Timings: LLM generation: {llm_time}ms, validation: {validation_time}ms, compilation: {compile_time}ms.",
        );

        Ok(())
    }

    // TODO: might want to rename this to `evolve`, and rename original `evolve` to something else. Backpressure should always be included in public method.
    /// Prompt the LLM, validate the response, compile, and hot-swap.
    ///
    /// If the constrained generation fails (parse error, signature mismatch,
    /// compilation failure), the error is appended to the prompt and the LLM
    /// retries until it produces valid code.
    ///
    /// # Contract
    ///
    /// All evolvable function calls must have returned before this is called.
    /// This is the natural shape of the feedback loop: run functions, collect
    /// results, evolve, repeat.
    pub async fn evolve_with_backpressure<CompletionModelT>(
        &self,
        agent: &Agent<CompletionModelT>,
        base_prompt: &str,
    ) -> Result<()>
    where
        CompletionModelT: CompletionModel + 'static,
    {
        let mut prompt = base_prompt.to_string();

        while let Err(e) = self.evolve(agent, &prompt).await {
            info!("Function evolution error: {e}.\nSelf-healing from error...");

            prompt = base_prompt.to_string();

            use Error::*;
            match e {
                    NoRustCode => prompt.push_str(
                        "Your response did not contain a rust code block. Please try again and make sure its wrapped like this: ```CODE```",
                    ),
                    CouldNotParseRust => prompt.push_str(
                        "Your response did not contain valid Rust code. Please try again",
                    ),
                    WriteLib(_) => todo!(),
                    SignatureMismatch {
                        name: _,
                        expected,
                        got,
                    } => write!(prompt,
                        " Generated function signature miss-match. Expected ```{expected}```, Got ```{got}```"
                    ).expect("Can write to prompt"),
                    CompilationFailed(ref stderr) => write!(prompt,
                        " The generated code failed to compile. Compiler output:\n```\n{stderr}\n```\nPlease fix the compilation errors."
                    ).expect("Can write to prompt"),
                    e => {
                        warn!("Unhandled error: {e}");
                        return Err(e)
                    },
                }
        }

        Ok(())
    }

    /// Path to the temporary crate directory.
    pub fn crate_dir(&self) -> &Path {
        &self.crate_dir
    }
}

fn generate_cargo_toml() -> String {
    r#"[package]
name = "symbiont-evolvable"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
"#
    .to_string()
}

fn generate_lib_rs(decls: &[EvolvableDecl]) -> String {
    decls
        .iter()
        .map(|d| d.default_source)
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn dylib_extension() -> &'static str {
    if cfg!(target_os = "macos") {
        ".dylib"
    } else if cfg!(target_os = "windows") {
        ".dll"
    } else {
        ".so"
    }
}

/// Find the compiled shared library in the temp crate's target directory.
fn find_so(crate_dir: &Path) -> Result<PathBuf> {
    let target_dir = crate_dir.join("target").join("debug");

    let prefix = if cfg!(target_os = "windows") {
        ""
    } else {
        "lib"
    };
    let name = format!("{prefix}symbiont_evolvable{ext}", ext = dylib_extension());
    let so_path = target_dir.join(&name);

    if so_path.exists() {
        Ok(so_path)
    } else {
        Err(Error::DylibLoad(format!(
            "Compiled dylib not found at {}",
            so_path.display()
        )))
    }
}
