// SPDX-License-Identifier: MPL-2.0
//! The runtime module contains the primary `Runtime`,
//! managing the lifecycle of the temporary dylib crate: creation, compilation,
//! loading, and hot-reloading.

use std::{
    collections::hash_map::DefaultHasher,
    fmt::Write,
    hash::{
        Hash,
        Hasher,
    },
    path::{
        Path,
        PathBuf,
    },
    sync::{
        Arc,
        OnceLock,
        RwLock,
        atomic::{
            AtomicPtr,
            AtomicU64,
            Ordering,
        },
    },
    time::Duration,
};

use libloading::Library;
use minstant::Instant;
use owo_colors::OwoColorize;
use prettyplease::unparse;
use rig_core::message::Message;
use tracing::{
    debug,
    info,
    warn,
};

use crate::{
    DylibConfig,
    EvolutionAgent,
    EvolvableDecl,
    FullSource,
    Profile,
    compiler::compile_dylib,
    error::{
        Error,
        Result,
    },
    parser::parse_rust_code,
    revision::{
        Revision,
        RevisionEntry,
        RevisionFn,
    },
    utils::{
        find_so,
        generate_cargo_toml,
        generate_lib_rs,
        is_context_size_error,
        is_transient_http_error,
        versioned_so_path,
    },
    validation::validate_generated_ast,
};

/// Singleton runtime instance.
static RUNTIME: OnceLock<Runtime> = OnceLock::new();

/// Cached pointer to the dylib's `__symbiont_take_panic` function.
/// Updated on each reload alongside the evolvable function pointers.
pub(crate) static TAKE_PANIC_PTR: AtomicPtr<()> = AtomicPtr::new(std::ptr::null_mut());

/// Manages the lifecycle of the temporary dylib crate: creation, compilation,
/// loading, and hot-reloading.
///
/// Function dispatch is lock-free: each evolvable function reads its cached
/// pointer via a single `AtomicPtr::load`.
///
/// Every successfully loaded dylib is retained in a keep-all revision
/// registry — see [`Revision`]. Earlier evolutions therefore stay loaded and
/// callable for the lifetime of the process, without ever parsing or
/// compiling them again.
///
/// # Contract
///
/// **All evolvable function calls must have returned before [`Runtime::evolve`]
/// is called.** This is the natural shape of the feedback loop — run functions,
/// collect results, evolve, repeat. The contract is enforced with an assertion
/// in debug builds and is zero-cost in release. Retained revisions are never
/// unmapped, so a violating in-flight call executes stale but still-mapped
/// code; the contract remains so a swap cannot tear a multi-function revision
/// apart mid-use.
pub struct Runtime {
    /// Path to the temporary dylib crate directory.
    crate_dir: PathBuf,
    /// Path to the unversioned `.so` / `.dylib` / `.dll` produced by cargo,
    /// used as the copy source for the per-revision versioned files.
    so_path: PathBuf,
    /// Function signatures for validation of LLM-generated code.
    fn_sigs: Vec<String>,
    /// Every successfully loaded dylib revision, retained for the lifetime of
    /// the process (keep-all). The index into this vec is the revision id.
    /// Entries are reference-counted so [`crate::RevisionFn`] handles can pin
    /// them. The lock is never taken on the hot path.
    revisions: RwLock<Vec<Arc<RevisionEntry>>>,
    /// Id of the revision currently published to the dispatch pointers.
    active: AtomicU64,
    /// Declarations (kept for fn_ptr updates on reload).
    decls: &'static [EvolvableDecl],
    /// Compilation profile (`debug` or `release`).
    profile: Profile,
    /// Rust source snippets prepended to the dylib's `lib.rs` on every
    /// (re)compilation. This includes inline items declared inside
    /// `evolvable! { ... }` and configured imports such as
    /// `use host::prelude::*;`.
    prelude: Vec<String>,
}

impl Runtime {
    /// Maximum number of attempts [`Runtime::evolve`] will make before giving
    /// up and returning [`Error::MaxRetriesExceeded`]. Prevents a misbehaving
    /// agent from hanging the runtime indefinitely.
    pub const MAX_EVOLVE_ATTEMPTS: usize = 10;

    /// Maximum number of retries for transient HTTP errors (429, 5xx, 529).
    ///
    /// These are retried with exponential backoff and do not count against
    /// [`Self::MAX_EVOLVE_ATTEMPTS`].
    pub const MAX_TRANSIENT_RETRIES: usize = 6;

    /// Initialize the symbiont runtime.
    ///
    /// Creates a temporary dylib crate from the declarations generated by `evolvable!`,
    /// compiles it, and loads the resulting shared library.
    ///
    /// Use [`Profile::Release`] when benchmarking evolved functions — the
    /// optimizer can make orders-of-magnitude difference for compute-heavy code.
    /// [`Profile::Debug`] compiles faster and is fine for correctness-only workloads.
    ///
    /// # Arguments:
    /// - `decls` should be the generated `SYMBIONT_DECLS` constant from the `evolvable` macro.
    /// - `generated_prelude` should be the generated `SYMBIONT_PRELUDE` constant from the macro.
    /// - `config` defines the compilation profile, dylib dependencies, and configured imports.
    ///
    /// # Panics
    ///
    /// Panics if called more than once.
    pub async fn new(
        decls: &'static [EvolvableDecl],
        generated_prelude: &'static [&'static str],
        config: impl Into<DylibConfig>,
    ) -> Result<&'static Runtime> {
        let config = config.into();
        if decls.is_empty() {
            return Err(Error::NoEvolvableFunctions);
        }

        let fn_sigs = Vec::from_iter(decls.iter().map(|d| d.signature.to_string()));

        // Create a stable temp directory based on function names
        let mut hasher = DefaultHasher::new();
        for d in decls {
            d.name.hash(&mut hasher);
        }
        let hash = hasher.finish();
        let crate_dir = std::env::temp_dir().join(format!("symbiont-evolvable-{hash:x}"));
        std::fs::create_dir_all(crate_dir.join("src"))?;

        // Write Cargo.toml
        let cargo_toml = generate_cargo_toml(config.dependencies(), config.patches());
        std::fs::write(crate_dir.join("Cargo.toml"), cargo_toml)?;

        let mut prelude = Vec::with_capacity(4);
        prelude.extend(
            generated_prelude
                .iter()
                .copied()
                .filter(|s| !s.is_empty())
                .map(str::to_owned),
        );
        prelude.extend(config.prelude().iter().cloned());

        // Write src/lib.rs from all default_source entries
        let lib_rs = generate_lib_rs(decls, &prelude);

        // Compile
        compile_dylib(&crate_dir, config.profile(), &lib_rs)?;

        // Copy the build output to the revision-0 path: later `cargo build`
        // runs replace the unversioned artifact, while the versioned copy
        // stays stable for the lifetime of the registry.
        let so_path = find_so(&crate_dir, config.profile())?;
        let v0_path = versioned_so_path(&crate_dir, Revision::INITIAL.as_u64());
        std::fs::copy(&so_path, &v0_path)?;
        let lib = unsafe {
            Library::new(&v0_path).map_err(|e| {
                Error::DylibLoad(format!("Failed to load {}: {e}", v0_path.display()))
            })?
        };

        // Resolve and cache the function pointers of the initial revision
        // (dispatch is lock-free after this point) and register it.
        let initial = unsafe { RevisionEntry::resolve(lib, decls, lib_rs)? };
        initial.publish(decls);

        let runtime = Runtime {
            crate_dir,
            so_path,
            fn_sigs,
            revisions: RwLock::new(vec![Arc::new(initial)]),
            active: AtomicU64::new(Revision::INITIAL.as_u64()),
            decls,
            profile: config.profile(),
            prelude,
        };

        RUNTIME
            .set(runtime)
            .map_err(|_| Error::AlreadyInitialized)?;
        Ok(RUNTIME.get().expect("just set"))
    }

    /// Generate LLM response, then parse, validate, compile, and hot-swap.
    /// It does not catch validation errors and feed it back to the LLM, allowing the user to customize prompting behaviour.
    ///
    /// On success, returns the [`Revision`] the new implementation was
    /// registered under.
    ///
    /// # Contract
    ///
    /// All evolvable function calls must have returned before this is called.
    /// In debug builds this is enforced with an assertion; in release it is
    /// the caller's responsibility.
    async fn evolve_no_backpressure<AgentT>(
        &self,
        agent: &AgentT,
        prompt: &str,
        history: &mut Vec<Message>,
    ) -> Result<Revision>
    where
        AgentT: EvolutionAgent,
    {
        Self::assert_no_calls_in_flight();

        info!("prompt: {}", prompt.green());
        let t0 = Instant::now();
        debug!("chat history: {history:?}");

        // The agent implementation drives any tool-calling turns to
        // completion internally and returns only the final text.
        let run = agent.run(prompt, history.clone()).await?;
        info!("llm_response: {}", run.output.blue());
        info!("token usage for this run: {:?}", run.usage);

        // `new_messages` contains the prompt, assistant turns and any
        // tool exchanges of this run, so extending is sufficient.
        history.extend(run.new_messages);
        let llm_response = run.output;
        let llm_time = t0.elapsed().as_millis();

        // Parse Rust from markdown fences
        let mut ast = parse_rust_code(&llm_response)?;

        // Validate signatures match declarations
        validate_generated_ast(&mut ast, &self.fn_sigs)?;

        // Re-inject the prelude (inline helper items and configured imports)
        // so the dylib still sees the same API surface used at initialization.
        // The LLM is asked to emit only the function bodies, so we control
        // the prelude here rather than relying on the model to repeat it.
        if !self.prelude.is_empty() {
            let mut combined: Vec<syn::Item> = Vec::new();
            for part in &self.prelude {
                if part.is_empty() {
                    continue;
                }
                let prelude_file: syn::File = syn::parse_str(part)
                    .expect("prelude was successfully parsed at init; should still be valid");
                combined.extend(prelude_file.items);
            }
            combined.append(&mut ast.items);
            ast.items = combined;
        }

        // Recompile
        let t0 = Instant::now();
        let clean_ast_str = unparse(&ast);
        debug!("clean_ast_str: {clean_ast_str}");
        compile_dylib(&self.crate_dir, self.profile, &clean_ast_str)?;
        let compile_time = t0.elapsed().as_millis();

        // Copy the build output to the next revision's own path (which also
        // defeats dlopen path caching) and load it.
        let id = self.next_revision_id()?;
        let versioned_so = versioned_so_path(&self.crate_dir, id);
        std::fs::copy(&self.so_path, &versioned_so)?;
        let new_lib = unsafe {
            Library::new(&versioned_so).map_err(|e| {
                Error::DylibLoad(format!("Failed to load {}: {e}", versioned_so.display()))
            })?
        };

        // Resolve the new revision's symbols, publish its function pointers
        // (atomic stores with Release ordering), and retain it in the
        // registry. The previous library stays loaded (keep-all), so earlier
        // revisions remain callable for the lifetime of the process.
        let entry = unsafe { RevisionEntry::resolve(new_lib, self.decls, clean_ast_str)? };
        entry.publish(self.decls);
        {
            let mut revisions = self.revisions.write().map_err(|_| Error::MutexPoison)?;
            debug_assert_eq!(
                u64::try_from(revisions.len()).expect("registry length fits in u64"),
                id,
                "concurrent evolve() calls are not supported"
            );
            revisions.push(Arc::new(entry));
        }
        self.active.store(id, Ordering::Release);

        info!(
            "Hot-reloaded evolvable dylib (revision {id}). Timings: LLM generation: {llm_time}ms, compilation: {compile_time}ms.",
        );

        Ok(Revision::new(id))
    }

    /// The id the next successfully loaded revision will be registered under.
    fn next_revision_id(&self) -> Result<u64> {
        let revisions = self.revisions.read().map_err(|_| Error::MutexPoison)?;
        Ok(u64::try_from(revisions.len()).expect("registry length fits in u64"))
    }

    /// Assert (debug builds only) that no evolvable function calls are in
    /// flight. Retained revisions are never unmapped, so a violation is no
    /// longer a use-after-unload — but a swap concurrent with running calls
    /// could still publish a torn set of pointers from two different
    /// revisions, so the feedback-loop contract remains.
    fn assert_no_calls_in_flight() {
        #[cfg(debug_assertions)]
        {
            use crate::debug_call_counter::IN_FLIGHT_CALLS;

            let in_flight = IN_FLIGHT_CALLS.load(Ordering::Acquire);
            assert!(
                in_flight == 0,
                "the active revision was swapped while {in_flight} evolvable function(s) are still executing. \
                 All callers must return before evolve() or activate_revision() — this is the feedback loop contract."
            );
        }
    }

    /// Exponential backoff (capped at 30s) for transient retry attempt `n`.
    fn transient_backoff(n: usize) -> Duration {
        let secs = 1u64 << n.min(5);
        Duration::from_secs(secs.min(30))
    }

    /// Prompt the LLM, validate the response, compile, and hot-swap.
    ///
    /// On success, returns the [`Revision`] the new implementation was
    /// registered under. The revision stays loaded for the lifetime of the
    /// process, so it can be pointed at again later.
    ///
    /// If constrained generation fails (parse error, signature mismatch, or
    /// compilation failure), the next turn contains only the latest correction;
    /// prior context remains available in chat history. The LLM retries until it
    /// produces valid code, up to [`Self::MAX_EVOLVE_ATTEMPTS`] attempts. After
    /// that, [`Error::MaxRetriesExceeded`] is returned so a
    /// misbehaving agent cannot hang the runtime indefinitely.
    ///
    /// The chat history is scoped to this call: it starts empty, accumulates
    /// the retry turns, and is discarded on return. Nothing carries over
    /// between `evolve` calls, so request sizes stay bounded in long-lived
    /// processes; callers that want cross-call continuity must render it
    /// into `base_prompt` themselves.
    ///
    /// Transient HTTP errors from the LLM provider (HTTP 429, 5xx, 529
    /// "overloaded") are retried separately with exponential backoff up to
    /// [`Self::MAX_TRANSIENT_RETRIES`] times, and do not count against the
    /// self-healing attempt budget.
    ///
    /// # Contract
    ///
    /// All evolvable function calls must have returned before this is called.
    /// This is the natural shape of the feedback loop: run functions, collect
    /// results, evolve, repeat.
    #[expect(
        clippy::manual_async_fn,
        reason = "Ensure the future is `Send` such that it works better with tokios multi-thread runtime"
    )]
    #[expect(
        clippy::too_many_lines,
        reason = "The retry policy is one sequential decision ladder; splitting it would obscure the order of the recovery rules"
    )]
    pub fn evolve<AgentT>(
        &self,
        agent: &AgentT,
        base_prompt: &str,
    ) -> impl Future<Output = Result<Revision>> + Send
    where
        AgentT: EvolutionAgent + Sync,
    {
        async move {
            let mut prompt = base_prompt.to_string();
            // Scoped to this call; see the doc comment above.
            let mut history: Vec<Message> = Vec::new();
            let mut attempts: usize = 0;
            let mut transient_attempts: usize = 0;

            loop {
                attempts += 1;
                match self
                    .evolve_no_backpressure(agent, &prompt, &mut history)
                    .await
                {
                    Ok(revision) => return Ok(revision),
                    Err(e) => {
                        // A request that exceeds the model's context window can
                        // never succeed by resending: shrink it instead.
                        // Discard the accumulated retry history and restart
                        // from the base prompt. If even a fresh request
                        // overflows (empty history), the base prompt itself is
                        // too large and only the caller can slim it down.
                        if is_context_size_error(&e) {
                            if history.is_empty() {
                                warn!(
                                    "Request exceeds the model's context window even without \
                                     chat history; the base prompt is too large: {e}"
                                );
                                return Err(e);
                            }
                            warn!(
                                "Request exceeded the model's context window; discarding {} \
                                 history messages and restarting from the base prompt",
                                history.len()
                            );
                            history.clear();
                            prompt.clear();
                            prompt.push_str(base_prompt);
                            // Not the LLM's fault: don't count against the
                            // self-healing budget.
                            attempts -= 1;
                            continue;
                        }

                        // Transient HTTP errors (rate limits, overload, gateway
                        // failures) are not the LLM's fault: retry with
                        // exponential backoff and don't count against the
                        // self-healing attempt budget.
                        if is_transient_http_error(&e) {
                            if transient_attempts >= Self::MAX_TRANSIENT_RETRIES {
                                warn!(
                                    "Transient HTTP error retry budget exhausted ({transient_attempts}/{}); giving up. Last error: {e}",
                                    Self::MAX_TRANSIENT_RETRIES
                                );
                                return Err(e);
                            }
                            let backoff = Self::transient_backoff(transient_attempts);
                            transient_attempts += 1;
                            warn!(
                                "Transient HTTP error from LLM provider (retry {transient_attempts}/{} in {:?}): {e}",
                                Self::MAX_TRANSIENT_RETRIES,
                                backoff,
                            );
                            // Don't count this against the self-healing budget.
                            attempts -= 1;
                            tokio::time::sleep(backoff).await;
                            continue;
                        }

                        if attempts >= Self::MAX_EVOLVE_ATTEMPTS {
                            warn!(
                                "Evolution failed after {attempts} attempts; giving up. Last error: {e}"
                            );
                            return Err(MaxRetriesExceeded {
                                attempts,
                                last_error: Box::new(e),
                            });
                        }

                        info!(
                            "Function evolution error (attempt {attempts}/{}): {e}.\nSelf-healing from error...",
                            Self::MAX_EVOLVE_ATTEMPTS
                        );

                        prompt.clear();

                        use Error::*;
                        match e {
                        NoRustCode => prompt.push_str(
                            "Your response did not contain a rust code block. Please try again and make sure its wrapped like this: ```CODE```",
                        ),
                        CouldNotParseRust { code, err } => write!(prompt,
                            "Your generated code ```{}``` is not valid Rust. Parse error: ```{}```. Fix the syntax error and respond with the full corrected code.", code.blue(), err.red()
                        ).expect("Can write to prompt"),
                        RigPrompt(rig_core::completion::PromptError::MaxTurnsError { .. }) => prompt.push_str(
                            "You exhausted the tool-call turn budget before producing code. Respond with the final Rust code block now.",
                        ),
                        WriteLib(_) => todo!(),
                        SignatureMismatch {
                            code,
                            expected,
                            got,
                        } => write!(prompt,
                            "Signature mismatch in {got}. Expected `{expected}`. Fix ONLY this function's signature (argument types and return type must match exactly; argument names may differ). Full code: ```{code}```",
                        ).expect("Can write to prompt"),
                        CompilationFailed{code, err} => write!(prompt,
                            "Your generated code ```{}``` failed to compile. Compiler output:\n```\n{}\n```\n\
                            Fix the compilation errors while preserving the existing logic and behaviour. \
                            Change only the expressions the compiler diagnostics point at (match the `src/lib.rs:<line>:<col>` markers); \
                            do not rewrite, restructure, rename, reformat or otherwise alter the rest of the code. \
                            A trait error (E0277) means you used an operator or conversion the type does not implement: \
                            consult the documented `impl ... for ...` blocks for that type and use only listed impls, \
                            adjusting the operand types instead of forcing an unsupported operation.",
                            code.blue(), err.red()
                        ).expect("Can write to prompt"),
                        e => {
                            warn!("Unhandled error: {e}");
                            return Err(e)
                        },
                    }
                    }
                }
            }
        }
    }

    /// Retrieve and clear the last panic message from the **active**
    /// revision's dylib.
    ///
    /// Returns `Some(message)` if the most recent evolvable function call
    /// panicked, `None` otherwise. The stored message is cleared on read.
    ///
    /// Call this after each evolvable function invocation to detect panics
    /// that were caught inside the dylib. Note that calls through a
    /// [`crate::RevisionFn`] handle store their panics in *that* revision's
    /// buffer — read those with [`crate::RevisionFn::take_panic`].
    pub fn take_panic(&self) -> Option<String> {
        let ptr = TAKE_PANIC_PTR.load(Ordering::Acquire);
        // SAFETY: TAKE_PANIC_PTR is only ever set from `__symbiont_take_panic`
        // symbols resolved out of libraries the registry keeps loaded.
        unsafe { crate::revision::read_panic_buffer(ptr.cast_const()) }
    }

    /// Path to the temporary crate directory.
    pub fn crate_dir(&self) -> &Path {
        &self.crate_dir
    }

    /// Get the function signature strings for all evolvable functions.
    pub fn fn_sigs(&self) -> &[String] {
        &self.fn_sigs
    }

    /// Get the prelude source injected into the generated dylib.
    ///
    /// This includes inline items from `evolvable!` and configured imports such
    /// as `use host::prelude::*;`.
    pub fn fn_prelude(&self) -> Vec<FullSource<'_>> {
        Vec::from_iter(self.prelude.iter().map(|v| FullSource(v)))
    }

    /// Get the full function signatures, including doc comments and default function body.
    ///
    /// Returns each source wrapped in [`FullSource`], which preserves real line
    /// breaks when pretty-printed (`{:#?}`) so logs stay readable.
    ///
    /// The other relevant imports/items that a function may require can be found in `fn_preludes`.
    pub fn fn_full_sources(&self) -> Vec<FullSource<'static>> {
        Vec::from_iter(self.decls.iter().map(|d| FullSource(d.full_source)))
    }

    /// Get the current, clean LLM-generated code (without panic-catching wrappers or preamble).
    /// Suitable for feeding back into the LLM prompt or displaying to the user.
    ///
    /// This is the source of the revision the dispatch pointers currently
    /// point at: the latest successful evolution.
    pub fn current_code(&self) -> String {
        self.revision_code(self.active_revision())
            .expect("the active revision is always registered")
    }

    /// The revision whose code the `evolvable!` dispatch wrappers currently
    /// execute.
    pub fn active_revision(&self) -> Revision {
        Revision::new(self.active.load(Ordering::Acquire))
    }

    /// Number of registered revisions: the initial build plus one per
    /// successful evolution. Valid revision ids are `0..revision_count()`.
    pub fn revision_count(&self) -> u64 {
        let revisions = self
            .revisions
            .read()
            .expect("revisions RwLock is not poisoned");
        u64::try_from(revisions.len()).expect("registry length fits in u64")
    }

    /// The clean generated source of `revision` (without panic-catching
    /// wrappers or preamble), or `None` if no such revision was registered.
    pub fn revision_code(&self, revision: Revision) -> Option<String> {
        let idx = usize::try_from(revision.as_u64()).ok()?;
        let revisions = self
            .revisions
            .read()
            .expect("revisions RwLock is not poisoned");
        revisions.get(idx).map(|entry| entry.source().to_owned())
    }

    /// Re-activate a previously registered revision.
    ///
    /// Republishes the revision's function pointers, which were resolved once
    /// when its dylib was first loaded: afterwards all `evolvable!` call
    /// sites dispatch to `revision`'s code and [`Runtime::current_code`]
    /// returns its source. No parsing or compilation is involved — the dylib
    /// has stayed loaded since it was hot-swapped, so activation costs a
    /// handful of atomic stores instead of an evolution round.
    ///
    /// Use it to roll back to the best revision a search discovered, to
    /// implement undo, or to re-deploy a known-good implementation for a
    /// final evaluation.
    ///
    /// Returns [`Error::UnknownRevision`] if `revision` was never registered;
    /// the active revision is left unchanged in that case.
    ///
    /// # Contract
    ///
    /// Same as [`Runtime::evolve`]: all evolvable function calls must have
    /// returned before this is called. Enforced with an assertion in debug
    /// builds, zero-cost in release.
    pub fn activate_revision(&self, revision: Revision) -> Result<()> {
        Self::assert_no_calls_in_flight();

        let revisions = self.revisions.read().map_err(|_| Error::MutexPoison)?;
        let entry = usize::try_from(revision.as_u64())
            .ok()
            .and_then(|idx| revisions.get(idx))
            .ok_or_else(|| Error::UnknownRevision {
                requested: revision,
                latest: Revision::new(
                    u64::try_from(revisions.len()).expect("registry length fits in u64") - 1,
                ),
            })?;
        entry.publish(self.decls);
        self.active.store(revision.as_u64(), Ordering::Release);
        info!("Activated revision {revision}.");
        Ok(())
    }

    /// Return the function signature and body for a single function base on its `fn_name`
    pub fn current_function(&self, fn_name: &str) -> Option<syn::ItemFn> {
        let code = self.current_code();
        let file: syn::File = syn::parse_str(&code).ok()?; // Its always valid code.
        file.items.into_iter().find_map(|item| match item {
            syn::Item::Fn(f) if f.sig.ident == fn_name => Some(f),
            _ => None,
        })
    }
}

/// Internal lookup behind the `<name>_fn` accessors generated by `evolvable!`:
/// resolve an untyped [`RevisionFn`] for the declaration whose dispatch static
/// is `fn_ptr_static` (identified by pointer identity, no strings involved).
///
/// Returns `None` if the runtime is not initialized, the declaration is not
/// registered, or `revision` does not exist. The generated accessor casts the
/// result to the concrete `fn` type it was expanded with.
///
/// Not part of the public API — used by `evolvable!` expansion.
#[doc(hidden)]
pub fn revision_fn_lookup(
    fn_ptr_static: &'static AtomicPtr<()>,
    revision: Revision,
) -> Option<RevisionFn<*const ()>> {
    let runtime = RUNTIME.get()?;
    let idx = runtime
        .decls
        .iter()
        .position(|decl| std::ptr::eq(decl.fn_ptr, fn_ptr_static))?;
    let revisions = runtime
        .revisions
        .read()
        .expect("revisions RwLock is not poisoned");
    let entry = revisions.get(usize::try_from(revision.as_u64()).ok()?)?;
    Some(RevisionFn::new_untyped(
        revision,
        entry.fn_ptr_at(idx),
        Arc::clone(entry),
    ))
}
