use std::{
    collections::hash_map::DefaultHasher,
    hash::{
        Hash,
        Hasher,
    },
    path::{
        Path,
        PathBuf,
    },
    sync::{
        OnceLock,
        RwLock,
        RwLockReadGuard,
        atomic::{
            AtomicU64,
            Ordering,
        },
    },
};

use tracing::info;

use crate::{
    EvolvableDecl,
    compiler::compile_dylib,
    error::{
        Error,
        Result,
    },
    parser::parse_rust_code,
    validation::validate_generated_ast,
};

/// Global handle to the currently loaded dylib.
///
/// Function wrappers generated by `evolvable!` take a read lock to call through.
/// [`Runtime::evolve`] takes a write lock to swap the library.
pub(crate) static DYLIB: RwLock<Option<libloading::Library>> = RwLock::new(None);

/// Singleton runtime instance.
static RUNTIME: OnceLock<Runtime> = OnceLock::new();

/// Acquire a read lock on the loaded dylib.
///
/// Called by the `evolvable!` macro-generated wrapper functions.
pub fn lib_read_lock() -> RwLockReadGuard<'static, Option<libloading::Library>> {
    DYLIB.read().expect("DYLIB RwLock poisoned")
}

/// Manages the lifecycle of the temporary dylib crate: creation, compilation,
/// loading, and hot-reloading.
pub struct Runtime {
    /// Path to the temporary dylib crate directory.
    crate_dir: PathBuf,
    /// Path to the compiled `.so` / `.dylib` / `.dll` file.
    so_path: PathBuf,
    /// Monotonically increasing version counter for versioned `.so` paths
    /// to defeat `dlopen` caching.
    version: AtomicU64,
    /// Function signatures for validation of LLM-generated code.
    fn_sigs: Vec<String>,
}

impl Runtime {
    /// Initialize the symbiont runtime.
    ///
    /// Creates a temporary dylib crate from the declarations generated by `evolvable!`,
    /// compiles it, and loads the resulting shared library.
    ///
    /// # Panics
    ///
    /// Panics if called more than once.
    pub async fn init(decls: &[EvolvableDecl]) -> Result<&'static Runtime> {
        if decls.is_empty() {
            return Err(Error::NoEvolvableFunctions);
        }

        let fn_sigs = Vec::from_iter(decls.iter().map(|d| d.signature.to_string()));

        // Create a stable temp directory based on function names
        let mut hasher = DefaultHasher::new();
        for d in decls {
            d.name.hash(&mut hasher);
        }
        let hash = hasher.finish();
        let crate_dir = std::env::temp_dir().join(format!("symbiont-evolvable-{hash:x}"));
        std::fs::create_dir_all(crate_dir.join("src"))?;

        // Write Cargo.toml
        let cargo_toml = generate_cargo_toml();
        std::fs::write(crate_dir.join("Cargo.toml"), cargo_toml)?;

        // Write src/lib.rs from all default_source entries
        let lib_rs = generate_lib_rs(decls);
        std::fs::write(crate_dir.join("src").join("lib.rs"), &lib_rs)?;
        info!("Created temp dylib crate at {}", crate_dir.display());

        // Compile
        compile_dylib(&crate_dir).await?;

        // Find and load the .so
        let so_path = find_so(&crate_dir)?;
        let lib = unsafe {
            libloading::Library::new(&so_path).map_err(|e| {
                Error::DylibLoad(format!("Failed to load {}: {e}", so_path.display()))
            })?
        };

        // Store in global
        *DYLIB.write().expect("DYLIB RwLock poisoned") = Some(lib);

        let runtime = Runtime {
            crate_dir,
            so_path,
            version: AtomicU64::new(1),
            fn_sigs,
        };

        RUNTIME
            .set(runtime)
            .map_err(|_| Error::AlreadyInitialized)?;
        Ok(RUNTIME.get().expect("just set"))
    }

    /// Get a function's signature string by name.
    pub fn fn_sigs(&self) -> &[String] {
        &self.fn_sigs
    }

    /// Process an LLM response: parse, validate, compile, and hot-swap.
    ///
    /// The `llm_response` should contain a Rust code block (optionally markdown-fenced)
    /// with implementations matching the declared evolvable function signatures.
    pub async fn evolve(&self, llm_response: &str) -> Result<()> {
        // Parse Rust from markdown fences
        let mut ast = parse_rust_code(llm_response).map_err(|_| Error::CouldNotParseRust)?;

        // Validate signatures match declarations
        validate_generated_ast(&mut ast, &self.fn_sigs)?;

        // Write validated AST to temp crate's lib.rs
        let lib_rs_path = self.crate_dir.join("src").join("lib.rs");
        let formatted = prettyplease::unparse(&ast);
        std::fs::write(&lib_rs_path, &formatted)
            .map_err(|e| Error::WriteLib(format!("Failed to write lib.rs: {e}")))?;
        info!("Wrote evolved lib.rs to {}", lib_rs_path.display());

        // Recompile
        compile_dylib(&self.crate_dir).await?;

        // Copy .so to versioned path to defeat dlopen caching
        let version = self.version.fetch_add(1, Ordering::SeqCst);
        let versioned_so = self.crate_dir.join(format!(
            "libsymbiont_evolvable_v{version}{}",
            dylib_extension()
        ));
        std::fs::copy(&self.so_path, &versioned_so)?;

        // Load new library
        let new_lib = unsafe {
            libloading::Library::new(&versioned_so).map_err(|e| {
                Error::DylibLoad(format!("Failed to load {}: {e}", versioned_so.display()))
            })?
        };

        // Swap under write lock
        {
            let mut guard = DYLIB.write().expect("DYLIB RwLock poisoned");
            let _old = guard.replace(new_lib);
            // Old library is dropped here. Safe because the write lock
            // guarantees no readers are executing code from the old library.
        }

        info!("Hot-reloaded evolvable dylib (version {version})");
        Ok(())
    }

    /// Path to the temporary crate directory.
    pub fn crate_dir(&self) -> &Path {
        &self.crate_dir
    }
}

fn generate_cargo_toml() -> String {
    r#"[package]
name = "symbiont-evolvable"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
"#
    .to_string()
}

fn generate_lib_rs(decls: &[EvolvableDecl]) -> String {
    decls
        .iter()
        .map(|d| d.default_source)
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn dylib_extension() -> &'static str {
    if cfg!(target_os = "macos") {
        ".dylib"
    } else if cfg!(target_os = "windows") {
        ".dll"
    } else {
        ".so"
    }
}

/// Find the compiled shared library in the temp crate's target directory.
fn find_so(crate_dir: &Path) -> Result<PathBuf> {
    let target_dir = crate_dir.join("target").join("debug");

    let prefix = if cfg!(target_os = "windows") {
        ""
    } else {
        "lib"
    };
    let name = format!("{prefix}symbiont_evolvable{ext}", ext = dylib_extension());
    let so_path = target_dir.join(&name);

    if so_path.exists() {
        Ok(so_path)
    } else {
        Err(Error::DylibLoad(format!(
            "Compiled dylib not found at {}",
            so_path.display()
        )))
    }
}
