base_url = "https://symbiont.rs"
build_search_index = false
compile_sass = true
description = "Agent harness for hot-reloadable function evolution in Rust"
generate_feeds = false
minify_html = true
title = "symbiont.rs"

[extra]
github_url = "https://github.com/MathisWellmann/symbiont"
